### ISSUE TITLE
ESP32 WEPAPP an ANY ADAU1452 BOARD

### ISSUE THREAD

**Issue by buraked-com** [freeDSP/freeDSP-aurora#86]
I can't find AK4458 and AK5558 in the market, I decided to use ADAU1966 in a circuit that I designed.
What features will not work in the ESP32 WEB APP if I do everything right?

**Comment by dspverden** [comment]
I cannot tell you that, I did not study the ADAU1966. The only device specific feature in the web app is the ADC channel summation which is done inside the AKM chip. And you have to update the chip configuration in the ESP firmware. 
But this is issue is not an issue of Aurora because you are developing your own hardware. Therefore, I close it now.
